/*
DDL (DATA DEFINITON LANGUAGE): 데이터 정의어

: 데이터베이스의 객체(테이블 사용자 뷰 인덱스 등)의 구조를 정의하거나 변경 삭제하는 명령어(SQL)
실제 데이터 값이 아닌 구조(규칙)을 정의

*/
--===========================

/*
테이블 생성 CREATE TABLE
CREATE TABLE 테이블 명(
컬럼명 데이터 타입
컬럼명 데이터 타입 DEFAULT 기본값,
컬럼명 데이터 타입 제약조건,
컬럼명 데이터 타입 DEFAULT 기본값 제약조건,
);
오라클 기본 자료형 (데이터타입)
-날짜 DATE 날짜및 시간 데이터
-숫자 NUMBER 숫자데이터 (정수, 실수)
-문자 CHAR(크기) 고정길이 2000BYE까지 지정한크기보다 작으면 공백으로 채워짐
VARCHAR2 가변길이 최대 4000바이트까지 입력된 데이터의 실제길이만큼의 공간 차지
*/
--회원(MEMBER) : 회원번호(MEM_NO) 회원ID(MEM_ID) 회원비밀번호(MEM_PWD) 회원이름(MEM_NAME)
--성별(GENDER) 연락처(PHONE) 이메일(EMAIL) 가입일시(ENROLLDATE)
CREATE TABLE MEMBER(
MEM_NO NUMBER,
MEM_ID VARCHAR2(20),
MEM_PWD VARCHAR2(20),
MEM_NAME VARCHAR2(20),
GENDER CHAR(3),--남또는 여
PHONE CHAR(15),
EMAIL VARCHAR2(41),
ENROLLDATE DATE
);

--컬럼에 주석 추가
-- 테이블에 컬럼이 무엇을 의미하는지 설명추가
-- COMMNET ON COLUMN 테이블명.컬럼명 IS '설명문구';
COMMENT ON COLUMN MEMBER.MEM_NO IS '회원번호';
COMMENT ON COLUMN MEMBER.MEM_ID IS '회원ID';
COMMENT ON COLUMN MEMBER.MEM_PWD IS '회원비밀번호';
COMMENT ON COLUMN MEMBER.MEM_NAME IS '회원이름';
COMMENT ON COLUMN MEMBER.GENDER IS '성별';
COMMENT ON COLUMN MEMBER.PHONE IS '연락처';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.ENROLLDATE IS '가입일시';

--데이터 추가 
INSERT INTO MEMBER VALUES (1,'MMPR','1234','이자성','남','010-1344-1598','MMEE.NAVER.COM',SYSDATE);

COMMIT;--변경사항적용

SELECT * FROM MEMBER;
/*
제약조건 테이블의 특정 컬럼에 부적절한 데이터가 들어오지 못하도록 설정하는 규칙
데이터 무결성 (정확성 일관성 신뢰성)을 보장하는것이 목적
설정 방식 종류
1 컬럼 레벨 방식 :  컬럼 정의 바로 옆에 제약조건을 기술하는 방식(모든 제약조건 설정 가능)
2 테이블 레벨 방식 : 모든 컬럼 정의을 마친후  하단에 별도로 기술하는 방식(NOT NULL제외)
*/
/*
NOT NULL 제약조건
해당 컬럼에 NULL값이 저장될수 업도록 제한
:필수적으로 입력되어야하는 데이터 아이디 비밀번호 연락처 등에 지정
=> 컬럼 레벨 방식으로만 지정할수있음
*/
---회원(MEMBER_NOTNULL) : 회원번호 (MEM_NO) 회원 아이디(MEM_ID) 비밀번호 (MEM_PWD) 이름(MEM_NAME) NOT NULL제약조건 설정
CREATE TABLE MEMBER_NOTNULL ( 
MEM_NO NUMBER NOT NULL,
MEM_ID VARCHAR2(20) NOT NULL,
MEM_PWD VARCHAR2(20) NOT NULL,
MEM_NAME VARCHAR2(20) NOT NULL,
GENDER CHAR(3),
PHONE CHAR(15),
EMAIL VARCHAR2(41),
ENROLLDATE DATE
);
INSERT INTO MEMBER_NOTNULL VALUES (1,'MMPR','1234','이자성','남','010-1344-1598','MMEE.NAVER.COM',SYSDATE);

SELECT * FROM MEMBER_NOTNULL;


/*
UNIQUE 제약조건 해당 컬럼에 중복된 데이터 값이 들어오는것을 제한
고유해야하는 데이터 (주민번호 아이디 이메일)에 적용
->NULL은 값이 없는 상태를 의미하므로 UNIQUE조건이 있어도 여러개 저장될수있음
보통 제약조건명을 지정하여 설정 에러 발생시 어떤 제약조건을 위배했는지 명확하게 파악하기위해
*/
--회원(MEMBER_UNIQUE) 회원아이데 UNIQUE 조건 설정

CREATE TABLE MEMBER_UNIQUE(
MEM_NO NUMBER NOT NULL,
MEM_ID VARCHAR2(20) NOT NULL,
MEM_PWD VARCHAR2(20) NOT NULL,
MEM_NAME VARCHAR2(20) NOT NULL,
GENDER CHAR(3),
PHONE CHAR(15),
EMAIL VARCHAR2(41),
ENROLLDATE DATE,
--컬럼 레벨방식 NOT NULL 번호 아이디 비밀번호 이름
---테이블 레벨 방식 UNIQUE(아이디)
CONSTRAINT UQ_MEM_ID UNIQUE(MEM_ID)
);

INSERT INTO MEMBER_UNIQUE VALUES (1,'MMPR','1234','이자성','남','010-1344-1598','MMEE.NAVER.COM',SYSDATE);
INSERT INTO MEMBER_UNIQUE VALUES (2,'MMPR','1234','이자성','남','010-1344-1598',NULL,NULL);
SELECT * FROM MEMBER_UNIQUE;

DROP TABLE MEMBER_UNIQUE;


----------------------------------------


/*
CHECK 제약 조건 해당 컬럼에 저장될수 있는 값범위나 특정 조건식을 지정해주는 규칙
조건식의 결과가 TRUE인 데이터만 저장할수있으며 NULL값도 저장 가능
*/
--회원(MEMBER_CHECK) : 성별(GENDER) '남' 또는 '여'값만 들어갈수있도록 조정
CREATE TABLE MEMBER_CHECK(
MEM_NO NUMBER NOT NULL,
MEM_ID VARCHAR2(20) NOT NULL,
MEM_PWD VARCHAR2(20) NOT NULL,
MEM_NAME VARCHAR2(20) NOT NULL,
GENDER CHAR(3) CONSTRAINT CK_GENDER CHECK (GENDER IN('남', '여')) ,
PHONE CHAR(15),
EMAIL VARCHAR2(41),
ENROLLDATE DATE,

CONSTRAINT UQ2_MEM_ID UNIQUE(MEM_ID)
);  

INSERT INTO MEMBER_CHECK VALUES (1,'MMPR','1234','이자성','남','010-1344-1598',NULL,NULL);

INSERT INTO MEMBER_CHECK VALUES (2,'MMPR','1234','이자성',NULL,'010-1344-1598',NULL,NULL);
SELECT * FROM MEMBER_CHECK;


/*
PRIMARY KEY (기본키) 제약조건
:테이블 내에서 각 행 고유하게 식별하기 위해 사용되는 대표 컬럼을 지정
NOT NULL + UNIQUE(NULL사용불가 중복불가)
테이블당 오직 1개만 가능

*/
--회원 회원 번호 컬럼을 기본키로 지정
CREATE TABLE MEMBER_PRI (
MEM_NO NUMBER CONSTRAINT PRI_NO PRIMARY KEY,
MEM_ID VARCHAR2(20) NOT NULL,
MEM_PWD VARCHAR2(20) NOT NULL,
MEM_NAME VARCHAR2(20) NOT NULL,
GENDER CHAR(3) CONSTRAINT CK2_GENDER CHECK (GENDER IN('남', '여')) ,
PHONE CHAR(15),
EMAIL VARCHAR2(41),
ENROLLDATE DATE,

CONSTRAINT UQ3_MEM_ID UNIQUE(MEM_ID)
);  

INSERT INTO MEMBER_PRI VALUES (1,'MMPR','1234','이자성','남','010-1344-1598',NULL,NULL);
INSERT INTO MEMBER_PRI VALUES (1,'MM2PR','1234','이자성','남','010-1344-1598',NULL,NULL);

/*
복합키 단일 컬럼만으로는 기본키 역할을 부여하기 애매할때
두개이상의 컬럼을 병합하여 하나의 기본키로 지정
=> 테이블 레벨 방식으로 설정 가능
*/

CREATE TABLE MEMBER_PRI2 (
MEM_ID VARCHAR2(20) NOT NULL,
MEM_PWD VARCHAR2(20) NOT NULL,
MEM_NAME VARCHAR2(20) NOT NULL,
GENDER CHAR(3) CHECK(GENDER IN('남', '여')) ,
PHONE CHAR(15),
EMAIL VARCHAR2(41),
ENROLLDATE DATE,

 UNIQUE(MEM_ID),
 CONSTRAINT PRI2_PK_IDPHONE PRIMARY KEY (MEM_ID,PHONE)
);  
INSERT INTO MEMBER_PRI2      VALUES ('MMPR','1234','이자성','남','010-1344-1598',NULL,NULL);

INSERT INTO MEMBER_PRI2      VALUES ('MM2PR','1234','이자성','남','010-1344-1598',NULL,NULL);

INSERT INTO MEMBER_PRI2      VALUES ('MM2PR','1234','이자성','남','010-1344-1598',NULL,NULL);

---------------------


/*
FOREIGN KEY 외래키 제약조건
다른 테이블에 존재하는 데이터 범위에서만 값을 저장하고자 할때 설정
테이블 간의 관계에 따라 지어
부모 테이블 참조대상  테이블 내 PK 또는 UNIQUE컬럼만 자식에게 제공할수있음
자식 테이블 (참조주체) 외래키 제약조건을 가지고 부모 컬럼을 가리키는 역할

*/
--부모테이블 회원 등급 (MEMBER_GRADE) - 등급번호(GRADE_NO)  등급명(GRADE_NAME)
CREATE TABLE MEMBER_GRADE(
GRADE_NO NUMBER PRIMARY KEY,
GRADE_NAME VARCHAR(20) NOT NULL
);

INSERT INTO MEMBER_GRADE VALUES (100,'일반회원');
INSERT INTO MEMBER_GRADE VALUES (200,'특별회원');
INSERT INTO MEMBER_GRADE VALUES (300,'특특별회원');

SELECT * FROM MEMBER_GRADE;

DROP TABLE MEMBER_FRK;

CREATE TABLE MEMBER_FRK (

MEM_NO NUMBER PRIMARY KEY,
MEM_ID VARCHAR(20) NOT NULL UNIQUE,
MEM_PWD VARCHAR(20) NOT NULL,
MEM_NAME VARCHAR(20) NOT NULL,
GENDER CHAR(3) CHECK (GENDER IN('남','여')),
ENROLLDATE DATE,
GRADE_ID NUMBER REFERENCES MEMBER_GRADE(GRADE_NO) ON DELETE SET NULL
);
INSERT INTO MEMBER_FRK VALUES (1,'MMPR','1234','이자성','남',SYSDATE, 100);
INSERT INTO MEMBER_FRK VALUES (2,'MM2PR','1234','이자','남',SYSDATE, 300);

SELECT* FROM MEMBER_FRK;
--삭제성공 자식테이블값은 NULL값으로 변경

--부모테이블에서  참조되고 있는 값을 삭제
DELETE FROM MEMBER_GRADE WHERE GRADE_NO = 100;
ROLLBACK;

/*
삭제 옵션 ON DELETE CASCADE
부모 테이블에서 특정행이 삭제될때 이를 참조하고있는 자식테이블
*/


----회원등급 테이블에서 등급번호  100번인 데이터 삭제
DELETE FROM MEMBER_GRADE WHERE GRADE_NO = 100;
--자식테이블이 존재해서 삭제 불가


--등급 테이블에서 200번 데이터 삭제
ROLLBACK;
DELETE FROM MEMBER_GRADE WHERE GRADE_NO = 300;

/*
삭제 옵션 ON DELETE SET NULL
부모 테이블에서 참조되고있는 행이 삭제될때 자식 테이블의 외래키 값을 자동으로 NULL로 변경
자식테이브의 데이터는 유지되고 관계만 정리할때사용
*/

CREATE TABLE MEMBER_FRK (

MEM_NO NUMBER PRIMARY KEY,
MEM_ID VARCHAR(20) NOT NULL UNIQUE,
MEM_PWD VARCHAR(20) NOT NULL,
MEM_NAME VARCHAR(20) NOT NULL,
GENDER CHAR(3) CHECK (GENDER IN('남','여')),
ENROLLDATE DATE,
GRADE_ID NUMBER REFERENCES MEMBER_GRADE(GRADE_NO) ON DELETE CASCADE
);
INSERT INTO MEMBER_FRK VALUES (1,'MMPR','1234','이자성','남',SYSDATE, 100);
INSERT INTO MEMBER_FRK VALUES (2,'MM2PR','1234','이자','남',SYSDATE, 300);
SELECT* FROM MEMBER_FRK;

DELETE FROM MEMBER_GRADE WHERE GRADE_NO 100;


/*
기본값 설정 DEFAULT
데이터가 추가될때 입력하지 않은 컬럼 값을 채워주기 위해 사용하는 옵션


*/

---회원(MEMBER_DEFAULT)

CREATE TABLE MEMBER_DEFAULT (
MEM_NO NUMBER PRIMARY KEY,
MEM_NAME VARCHAR(20) NOT NULL,
AGE NUMBER,
HOBBY VARCHAR(30) DEFAULT '없음',
ENROLLDATE DATE DEFAULT SYSDATE

);
INSERT INTO MEMBER_DEFAULT VALUES (1, '박문수', 20, '코딩', SYSDATE);

INSERT INTO MEMBER_DEFAULT  (MEM_NO, MEM_NAME, AGE) VALUES (2, '박문수', 20 );
INSERT INTO MEMBER_DEFAULT VALUES (3, '박수진', 20, NULL, NULL);

SELECT * FROM MEMBER_DEFAULT;
----------------------------------------

/*
테이블 복제
기존에 구현되어있는 다른 테이블구성과 데이터를 빠르게 가져와서 새로운 복제본 테이블을 만드는 방법
컬럼 크기 자료형 데이터 자체는 복제가되지만 NOT NULL 제외 제약조건은 복제되지않는다.

CREATE 테이블명
AS 서브쿼리
*/
CREATE TABLE MEMBER_COPY
AS (
SELECT * FROM EMPLOYEE
);
SELECT * FROM EMP_INFO;

CREATE TABLE EMP_INFO
AS (
SELECT EMP_ID, EMP_NAME, SALARY
FROM EMPLOYEE);

DROP TABLE EMP_INFO;

CREATE TABLE EMP_INFO
AS (
SELECT EMP_ID, EMP_NAME, SALARY
FROM EMPLOYEE WHERE 1=0);
SELECT * FROM EMP_INFO;

/*
ALTER 구조변경시 사용하는 구문
ALTER TABLE
기존에 생성되어있는 테이블 컬럼 제약조건을 변경하는구문
컬럼 추가 수정 삭제 제약조건 추가 삭제
*/

--DEPT_TABLE 테이블 생성 (DEPT_ID 고정길이 DEPT_TITLE 가변길이(35)

CREATE TABLE DEPT_TABLE (
DEPT_ID CHAR(5),
DEPT_TITLE VARCHAR2(35)
);

ALTER TABLE DEPT_TABLE ADD CNAME VARCHAR2(20); 
ALTER TABLE DEPT_TABLE ADD LNAME VARCHAR2(20) DEFAULT '한국';

/*
컬럼변경
ALTER TABLE 테이블명 MODIFY 변경할컬럼명 변경할 데이터타입 DEFAULT 기본값

*/
--DEPT 테이블의 DEPT ID의 컬럼의 데이터타입 10으로 변경

ALTER TABLE DEPT_TABLE MODIFY DEPT_ID CHAR(10);

---여러개의 컬럼을 한번에 변경 할수있음
-- DEPT_TITLE 컬럼의 데이터 타입 가변길이 55로 변경
--LNAME컬럼 기본값을 KOREA

ALTER TABLE DEPT_TABLE MODIFY DEPT_TITLE VARCHAR2(55);
ALTER TABLE DEPT_TABLE MODIFY LNAME DEFAULT 'KOREA';

--컬럼 삭제

--ALTER TABLE 테이블명 DROP COLUMN 컬럼명
--삭제후 복구불가 유의

--LNAME삭제

ALTER TABLE DEPT_TABLE DROP COLUMN LNAME;

/*
제약조건 추가
ALTER TABLE 테이블명 ADD 제약조건(컬럼명)

*/

--DEPT_TABLE의 DEPT_ID 컬럼을 기본키로 설정 제약조건명 PK_DT
ALTER TABLE DEPT_TABLE ADD CONSTRAINT PK_DT PRIMARY KEY (DEPT_ID);

--DEPT_TITLE 컬럼  중복 불가로 제약조건명 UQ_DT

ALTER TABLE DEPT_TABLE ADD CONSTRAINT UQ_DT UNIQUE(DEPT_TITLE);

--NOT NULL
ALTER TABLE DEPT_TABLE MODIFY CNAME NOT NULL;

/*
제약조건 삭제
ALTER TABLE 테이블명 DROP CONSTRAINT 제약조건명
*/
--기본키 삭제
ALTER TABLE DEPT_TABLE DROP CONSTRAINT PK_DT;

ALTER TABLE DEPT_TABLE DROP CONSTRAINT UQ_DT;

ALTER TABLE DEPT_TABLE MODIFY CNAME NULL;

/*
이름 변경
ALTER TABLE 테이블명 RENAME COLUMN 기존컬럼명 TO 변경할컬럼명
ALTER TABLE 테이블명 RENAME CONSTRAINT 기존제약조건명 TO 변경할제약조건명
ALTER TABLE 기존 테이블명 RENAME TO 변경할테이블명
*/

--컬럼명 변경 (DEPT_TABLE : DEPT_TITLE DEPT_NAME)

ALTER TABLE DEPT_TABLE RENAME COLUMN DEPT_TITLE TO DEPT_NAME;


ALTER TABLE DEPT_TABLE ADD CONSTRAINT PR PRIMARY KEY (DEPT_ID);

ALTER TABLE DEPT_TABLE RENAME CONSTRAINT PR TO PK_DT;

--테이블명 변경

ALTER TABLE DEPT_TABLE RENAME TO DEPT_TEST;


/*
DROP TABLE 테이블명 : 해당 테이블을 완전히 삭제


*/
--DEPT_TEST를 DEPT_COPY로 복제

CREATE TABLE DEPT_COPY
AS(SELECT * FROM DEPT_TEST);
DROP TABLE DEPT_COPY;
DROP TABLE MEMBER_GRADE;

--- 관계설정 상관없이 삭제시 CASCADE사용
DROP TABLE MEMBER_GRADE CASCADE CONSTRAINTS;x`
