/*
SQL

DQL (QUERY 데이터 질의 언어) 데이터 조회 SELECT
DDL (DEFINITION 데이터 정의 언어) 구조 규칙 관리 CREATE ALTER DROP
DML (MANIPULATION 데이터 조작 언어) INSERT UPDATE DELETE
TCL (TRANSACTION CONTROL 트렌젝션 제어언어) COMMIT ROLLBACK
DCL (CONTROL 데이터 제어언어) : GRANT REVOKE
*/

----------------------------

/*
DML 테이블에 데이터를 추가하거나 INSERT 변경하거나 UPDATE 삭제 DELETE하기위한 언어

*/
-- INSERT 테이블에 새로운 행을 추가하는 구문
--INSERT INTO 테이블명 VALUES (값, 값, 값,...)
--테이블의 모든 컬럼에 대한 값을 직접 제시하여 추가하고자 할때 사용
--순서에 맞게 나열해야함
--값을 부족하게 제시할경우 NOT ENOUGH VALUE
--더많을 경우 TOO MANY VALUE

--EMPLOYEE 테이블 추가
SELECT*FROM EMPLOYEE;

INSERT INTO EMPLOYEE VALUES (900, '장현우', '880709-1056413', 'hw000kh.or.kr',NULL,'D4','J4',4000000,0.3,NULL,SYSDATE,NULL,'N');
/*
INSERT INTO 테이블명 (컬럼명1 컬럼명2 컬럼명3
VALUES (값1,값2,값3...)
컬럼을 직접 제시하여 해당 컬럼에 값을 추가
제시하지 않은 컬럼에 대한 값은 기본적으로 NULL값이 저장되고 
NULL 값이 아닌 저장하고자 할때는 기본값 옵션 (DEFAULT)를 설정해야한다
제시하지 않은 컬럼에 "NOT NULL"제약 조건이 있다면
반드시 값을 직접 제시하거나 또는 기본값 옵션을 추가해야함
*/
INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, EMP_NO, EMAIL, JOB_CODE)
VALUES(901,'공윤정','040709-4445555','yj04@kh.or.kr','J4');


/*
 INSERT INTO 테이블명 (서브쿼리)
 VALUES로 값을 직접명시하는 대신 서브쿼리로 조회된 결과값을 통째로 INSERT하는 방법
*/
    --EMP01 테이블 추가
    --직원번호 이름 부서명
    
    CREATE TABLE EMP01 (
    EMP_ID VARCHAR2(3),
    EMP_NAME VARCHAR2(20),
    EMP_TITLE VARCHAR2(35)
    );
    SELECT * FROM EMP01;
    
    --- 직원번호 이름 부서명 조회
    SELECT EMP_ID, EMP_NAME, DEPT_TITLE
    FROM EMPLOYEE, DEPARTMENT
    WHERE DEPT_ID(+) = DEPT_CODE;
    
SELECT EMP_ID, EMP_NAME, DEPT_TITLE
FROM EMPLOYEE LEFT JOIN DEPARTMENT ON  DEPT_ID = DEPT_CODE;
--EMP01 테이블에 데이터 추가
INSERT INTO EMP01
(
SELECT EMP_ID, EMP_NAME, DEPT_TITLE
FROM EMPLOYEE LEFT JOIN DEPARTMENT ON  DEPT_ID = DEPT_CODE
);

/*
    INSERT ALL 두개이상의 테이블에 각각 데이터를 추가할때 사용 사용되는 서브쿼리가 동일한 경우 적용하는 방법
    
    INSERT ALL
    INTO 테이블명 VALUES (컬럼명, 컬럼명)
     INTO 테이블명2 VALUES (컬럼명, 컬럼명)
     (서브쿼리)
     VALUES 다음에 작성하는 컬럼명은 서브쿼리의 결과 에 표시되는 컬럼명이어야함


*/



--EMP_DEPT 테이블  : 직원번호ID 이름 부서코드 입사일

CREATE TABLE EMP_DEPT AS( SELECT EMP_ID, EMP_NAME, DEPT_CODE, HIRE_DATE FROM EMPLOYEE WHERE 1=0);
SELECT * FROM EMP_DEPT;

INSERT ALL INTO EMP_DEPT VALUES (EMP_ID,EMP_NAME, DEPT_CODE, HIRE_DATE)
(SELECT EMP_ID, EMP_NAME, DEPT_CODE, HIRE_DATE FROM EMPLOYEE);
DROP TABLE EMP_MANAGER;
CREATE TABLE EMP_MANAGER AS( SELECT EMP_ID, EMP_NAME, MANAGER_ID FROM EMPLOYEE WHERE 1=0);
SELECT * FROM EMP_MANAGER;

SELECT EMP_ID, EMP_NAME, DEPT_CODE,MANAGER_ID,HIRE_DATE
FROM EMPLOYEE
WHERE DEPT_CODE = 'D1';

INSERT ALL 
INTO EMP_DEPT VALUES (EMP_ID,EMP_NAME, DEPT_CODE, HIRE_DATE)
INTO EMP_MANAGER VALUES (EMP_ID,EMP_NAME, MANAGER_ID)
(SELECT EMP_ID, EMP_NAME, DEPT_CODE,MANAGER_ID,HIRE_DATE
FROM EMPLOYEE
WHERE DEPT_CODE = 'D1');
SELECT* FROM EMP_DEPT;

/*
UPDATE 테이블에 저장되어 있는 기존 데이터를 변경하는 구문
UPDATE 테이블 명
SET 컬럼명 = 변경할값
    컬럼명 = 변경할값
    WHERE 조건식
    SET절에는 여러 개의 컬럼을 동시에 변경 가능 콤마로 나열해야함
    WHERE 절을 생략했을 경우 테이블의 모든 행이 변경됨
    
    */
    
    --DEPT_TABLE에 DEPARTMENT 테이블을 복제
     
CREATE TABLE DEPT_TABLE AS ( SELECT * FROM DEPARTMENT);
SELECT * FROM DEPT_TABLE;
--부서코드가 D1인 부서명을 '인사팀'으로 변경

UPDATE DEPT_TABLE
SET DEPT_TITLE = '인사팀'
WHERE DEPT_ID = 'D1';


---------
--부서명 총무부를 전략기획팀

UPDATE DEPT_TABLE
SET DEPT_TITLE = '전략기획팀'
WHERE DEPT_ID = 'D9';


----EMP_TABLE   EMPLOYEE 복제

CREATE TABLE EMP_TABLE AS (SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY, BONUS FROM EMPLOYEE);

--직원번호 900번이 회사의 급여를 500만원으로 인상

UPDATE EMP_TABLE
SET SALARY = 5000000
WHERE EMP_ID = 900;

SELECT * FROM EMP_TABLE;

UPDATE EMP_TABLE
SET SALARY = 4500000,BONUS = 0.2
WHERE EMP_NAME = '대북혼';

--전체 직원의 급여를 10프로 인상
UPDATE EMP_TABLE
SET SALARY = SALARY * 1.1;

/*
UPDATE 문에 서브쿼리 사용하기
UPDATE 테이블명
SET 컬럼명  = (서브쿼리)
WHERE 조건

*/

SELECT SALARY, BONUS
FROM EMP_TABLE
WHERE EMP_NAME = '방명수';

SELECT SALARY, BONUS
FROM EMP_TABLE
WHERE EMP_NAME = '유재식';

UPDATE EMP_TABLE
SET SALARY = (SELECT SALARY
FROM EMP_TABLE
WHERE EMP_NAME = '유재식'),
BONUS = (SELECT BONUS
FROM EMP_TABLE
WHERE EMP_NAME = '유재식')
WHERE EMP_NAME = '방명수';
SELECT * FROM EMP_TABLE;


SELECT *
FROM EMP_TABLE
WHERE (SALARY, BONUS) = (SELECT SALARY, BONUS
FROM EMP_TABLE
WHERE EMP_NAME = '유재식');

UPDATE EMP_TABLE
SET (SALARY, BONUS) = (SELECT SALARY, BONUS
FROM EMP_TABLE
WHERE EMP_NAME = '유재식')
WHERE EMP_NAME = '윤은해';

--ASIA 지역에서 근무중인 직원들의 보너스를 0.3

SELECT * FROM LOCATION WHERE LOCAL_NAME LIKE 'ASIA%';

SELECT*
FROM DEPARTMENT
JOIN LOCATION ON LOCATION_ID = LOCAL_CODE
WHERE  LOCAL_NAME LIKE 'ASIA%';


UPDATE EMP_TABLE
SET BONUS = 0.3
WHERE EMP_ID IN (SELECT EMP_ID
FROM EMP_TABLE
JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID JOIN LOCATION ON LOCATION_ID = LOCAL_CODE
WHERE LOCAL_NAME LIKE 'ASIA%');

/*
DELETE 테이블에 저장되어 있는 데이터를 삭제할때 사용하는 구문

DELETE FROM 테이블명
[WHERE 조건]
WHERE 절 생략시 모든 데이터 삭제


*/


DELETE FROM EMPLOYEE;

SELECT* FROM EMPLOYEE;

ROLLBACK;


--901번 데이터를 삭제
DELETE FROM EMP_TABLE WHERE EMP_ID = '901';
SELECT* FROM EMP_TABLE;

DELETE FROM EMP_TABLE WHERE EMP_NAME = '장현우';

/*
TRUNCATE : 테이블의 전체행을 삭제할때 사용하는 DDL 롤백 불가
별도의 조건 제시 불가
TRUNCATE TABLE 테이블명
*/
TRUNCATE TABLE EMP_TABLE;
DROP TABLE EMP_TABLE;



