/*
VIEW (뷰)
:SELECT문을 저장해둘수있는 객체
=> 자주 사용되는 길고 복잡한 쿼리문을 저장해두면 매번 다시 작성할 필요가 없음
일종의 임시 테이블 역할 (SQL(SELECT)문만 저장함)

*/

--직원 부서 직급 지역 국가 급여등급
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, SALARY, NATIONAL_NAME
FROM EMPLOYEE JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID JOIN LOCATION ON LOCAL_CODE = LOCATION_ID JOIN NATIONAL USING (NATIONAL_CODE)
WHERE NATIONAL_NAME = '러시아';

/*
VIEW 생성하기

CREATE (OR REPLACE) VIEW 뷰명
AS 서브쿼리;
=뷰 객체를 생성할때는 서브쿼리에 괄호를 쓰지않는다

참고 이름 표기 규칙
테이블 : TB_XX
뷰: VW_XX
*/

--VW_EMPLOYEE 뷰 객체 생성
CREATE OR REPLACE VIEW VW_EMPLOYEE
AS
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, SALARY, NATIONAL_NAME
FROM EMPLOYEE JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID JOIN LOCATION ON LOCAL_CODE = LOCATION_ID JOIN NATIONAL USING (NATIONAL_CODE);

--처음뷰생성시 권한부족오류가 발생할수있음

GRANT CREATE VIEW TO C##KH;

SELECT*FROM USER_VIEWS;

SELECT*FROM VW_EMPLOYEE;

SELECT *
FROM (
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, SALARY, NATIONAL_NAME
FROM EMPLOYEE JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID JOIN LOCATION ON LOCAL_CODE = LOCATION_ID JOIN NATIONAL USING (NATIONAL_CODE)
);
SELECT*FROM VW_EMPLOYEE WHERE NATIONAL_NAME ='한국';

SELECT EMP_ID, JOB_NAME, DECODE(SUBSTR(EMP_NO,8,1),'1','남','2','영','3','남','4','여'), FLOOR((SYSDATE - HIRE_DATE )/365) 근무년수 //EXTRACT(YEAR FROM SYSYDATE) - EXTRACT(YEAR FROM HIRE_DATE)
FROM EMPLOYEE JOIN JOB USING (JOB_CODE);

CREATE OR REPLACE VIEW VW_EMPNO
AS
SELECT EMP_ID, JOB_NAME, DECODE(SUBSTR(EMP_NO,8,1),'1','남','2','영','3','남','4','여'), FLOOR((SYSDATE - HIRE_DATE )/365) 근무년수 
FROM EMPLOYEE JOIN JOB USING (JOB_CODE);
--함수문 연산식이 들어간 컬럼은 반드시 별칭을 부여해야한다

--별칭 부여  1) 서브쿼리에 별칭부여
CREATE OR REPLACE VIEW VW_EMPNO
AS
SELECT EMP_ID, JOB_NAME, DECODE(SUBSTR(EMP_NO,8,1),'1','남','2','영','3','남','4','여') 성별, FLOOR((SYSDATE - HIRE_DATE )/365) 근무년수 
FROM EMPLOYEE JOIN JOB USING (JOB_CODE);

-- 별칭부여 2 뷰이름 선언시 컬럼명 정의
CREATE OR REPLACE VIEW VW_EMPNO (직원번호, 직급명, 성별, 근무년수)
AS
SELECT EMP_ID, JOB_NAME, DECODE(SUBSTR(EMP_NO,8,1),'1','남','2','여','3','남','4','여'), FLOOR((SYSDATE - HIRE_DATE )/365) 
FROM EMPLOYEE JOIN JOB USING (JOB_CODE);

SELECT* FROM VW_EMPNO WHERE 성별 = '여';
SELECT* FROM VW_EMPNO WHERE 근무년수 >= 20;

/*
생성된 뷰를 통해 DML(INSERT/UPDATE/DELETE) 수행하기
뷰는 가상 테이블이므로 뷰를 통해 DML을 수행하면 원본 테이블의 데이터가 변경됨
*/
--JOB테이블을 뷰로 생성
CREATE OR REPLACE VIEW VW_JOB
AS SELECT JOB_CODE, JOB_NAME FROM JOB;

SELECT EMAIL,
       INSTR(EMAIL, '@', 1, 1) AS "골뱅이 위치"
FROM EMPLOYEE;

UPDATE VW_JOB SET JOB_NAME = '알바' WHERE JOB_CODE = 'J8';
DELETE FROM VW_JOB WHERE JOB_CODE = 'J8';

INSERT INTO VW_JOB VALUES('J8','인턴');
SELECT * FROM VW_JOB;

ROLLBACK;

/*
뷰를 통한 DML 변경이 불가능한경우(제한되는경우)
뷰에 포함되지 않는 테이블의 컬럼이 NOT NULL제한조건이 있는경우
산술연산식이나 함수식으로 만들어진 컬럼을 수정하려할때
중복제거구문이 포함된경우
GROUP BY/ HAVING등 집계함수가 포함된경우
2개이상의 테이블을 JOIN하여 만든 복합 SELECT문인경우
뷰는 대부분 SELECT  전용인경우가 관례이고 안전하다
*/

/* 뷰생성옵션
FORCE 테이블이 없어도 뷰를 강제 생성
WITH CHECK OPTION : VIEW(서브쿼리)의 조건절에 위배되는 데이터 조작(DML)을 차단
WITH READ ONLY : DML 조작을 원천 차단하고 오직 SELECT만 허용
*/

--FORCE 옵션
CREATE OR REPLACE FORCE VIEW VW_TEST
AS SELECT TE_ID, TE_NAME FROM TETE;

SELECT * FROM VW_TEST;


---WITH CHECK OPTION

CREATE OR REPLACE VIEW VW_EMP_SAL
AS SELECT * FROM EMPLOYEE WHERE SALARY >= 3000000
WITH CHECK OPTION;

--204번 직원 급여를 200만원으로 변경

UPDATE VW_EMP_SAL
SET SALARY = 2000000
WHERE EMP_ID = '204';

--- WITH READ ONLY  

CREATE OR REPLACE VIEW VW_EMP_SAL
AS SELECT * FROM EMPLOYEE WHERE SALARY >= 3000000
WITH READ ONLY;

SELECT* FROM VW_EMP_SAL;

DELETE FROM VW_EMP_SAL WHERE EMP_ID = '200';




