/*
JOIN 여러개의 테이블을 연결 하여 하나의 가상 테이블처럼 조회하는 구문


*/

--직원 정보 조회 (직원번호 이름 부서코드)

SELECT EMP_ID, EMP_NAME, DEPT_CODE
FROM EMPLOYEE;

--부서 정보 조회

SELECT *
FROM DEPARTMENT;


SELECT DEPT_ID, DEPT_TITLE
FROM DEPARTMENT;

SELECT EMP_ID, EMPT_NAME, DEPT_ID
FROM EMPLOYEE, DEPARTMENT;
--오라클 전용구문
--FROM 절에 조회하고자하는 테이블 나열
--WHERE 절에 조인 조건 작성
SELECT EMP_ID, EMP_NAME, DEPT_TITLE
FROM EMPLOYEE, DEPARTMENT
WHERE DEPT_CODE = DEPT_ID;

---EMPLYOEE 테이블에서 부서코드 NULL인 직원은 결과에서 제외
---DEPARTMENT D3 D4 D7 직원이 EMPLOYEE에 존재하지않아 제외
--직원 번호 이름 직급명 조회
SELECT JOB_CODE, JOB_NAME
FROM JOB;


SELECT EMP_ID, EMP_NAME, JOB_NAME
FROM EMPLOYEE E, JOB J
WHERE E.JOB_CODE =J.JOB_CODE;


--ANSI 구문
--FROM 절에 기준이 되는 테이블 작성
--JOIN 절에 연결하고자 하는 테이블 작성 + 조인조건 작성
-- USING 컬럼명이 동일한 경우
-- ON 컬럼명이 동일하거나 다른경우

--직원번호 이름 부서명
SELECT EMP_ID, EMP_NAME, DEPT_TITLE
FROM EMPLOYEE JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID;

--직원 번호 이름 직급명 조회
SELECT EMP_ID, EMP_NAME, JOB_NAME
FROM EMPLOYEE JOIN JOB USING (JOB_CODE);

SELECT EMP_ID, EMP_NAME, JOB_NAME
FROM EMPLOYEE E JOIN JOB J ON E.JOB_CODE = J.JOB_CODE;

/*
포괄 조인 외부 조인 (OUTER JOIN)
두테이블을 조인할때 조인 조건에 맞지 않는 행도 결과에 포함하는 구문

-LEFT OUTER JOIN 두 테이블 중 왼쪽에 작성된 테이블을 기준으로 조인
(왼쪽 테이블의 모든 행 + 조건에 맞는 오른쪽 테이블행)
RIGHT OUTER JOIN 두 테이블 중 오른쪽에 작성된 테이블을 기준으로 조인
오른쪽 테이블의 모든행 + 조건에 맞는 왼쪽 테이블행
FULL OUTER JOIN 두 테이블이 가진 모든 해을 조회하는 구문( 오라클 전용 구문 X)
*/
--오라클 구문
--추가로 연결되는 테이블에 해당하는 컬럼 옆에 (+) 기호를 붙여 표현
-- 이름 부서명 급여 정보 조회
SELECT EMP_NAME, DEPT_TITLE, SALARY
FROM EMPLOYEE, DEPARTMENT
WHERE DEPT_CODE = DEPT_ID(+);

---ANSI 구문
SELECT EMP_NAME, DEPT_TITLE, SALARY
FROM EMPLOYEE JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID;

--RIGH JOIN
SELECT EMP_NAME, DEPT_TITLE, SALARY
FROM EMPLOYEE, DEPARTMENT
WHERE DEPT_CODE(+) = DEPT_ID;

--ANSI 구문
SELECT EMP_NAME, DEPT_TITLE, SALARY
FROM EMPLOYEE RIGHT JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID;

---FULL OUTER JOIN
--ANSI 구문
--이름 부서명 급여 조회 (모든 직원 모든 부서)
SELECT EMP_NAME, DEPT_TITLE, SALARY
FROM EMPLOYEE FULL JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID;

-- 비등가 조인
-- 조인 조건에 = 대신  > < BETWEEN LIKE등 비교연산자 사용
--ANSI 구문에서는 JOIN ON만 사용가능
--직원에 대한 급여 등급 조회 이름 급여 등급
--오라클 구문
SELECT EMP_NAME, SALARY, SAL_LEVEL
FROM EMPLOYEE, SAL_GRADE
WHERE SALARY >= MIN_SAL AND SALARY <= MAX_SAL;

--ANSI
SELECT EMP_NAME, SALARY, SAL_LEVEL
FROM EMPLOYEE 
--JOIN SAL_GRADE ON SALARY >= MIN_SAL AND SALARY <= MAX_SAL;
JOIN SAL_GRADE ON SALARY BETWEEN MIN_SAL AND MAX_SAL;

/*
자체 조인/ 셀프 조인
하나의 테이블을 마치 서로 다른 테이블처럼 별칭을 주어 조인하는 구문
테이블 내에 자기 자신 관계가 있는 데이터를 조회 할때 사용
*/

--전체 직원의 직원번호 이름 부서 코드
--사수직원번호 사수명 사수부서 코드 조회

--직원 정보 => EMPLOYEE / 사주 직원 정보 => EMPLOYEE
SELECT E.EMP_ID, E.EMP_NAME, E.DEPT_CODE, M.EMP_ID, M.EMP_NAME, M.DEPT_CODE 
FROM EMPLOYEE E, EMPLOYEE M
WHERE E.MANAGER_ID = M.EMP_ID;

--ANSI 구문
SELECT E.EMP_ID, E.EMP_NAME, E.DEPT_CODE, M.EMP_ID, M.EMP_NAME, M.DEPT_CODE 
FROM EMPLOYEE E JOIN EMPLOYEE M ON E.MANAGER_ID = M.EMP_ID;

--사수가 없는 직원도 조회
SELECT E.EMP_ID, E.EMP_NAME, E.DEPT_CODE, M.EMP_ID, M.EMP_NAME, M.DEPT_CODE 
FROM EMPLOYEE E LEFT JOIN EMPLOYEE M ON E.MANAGER_ID = M.EMP_ID;

SELECT E.EMP_ID, E.EMP_NAME, E.DEPT_CODE, M.EMP_ID, M.EMP_NAME, M.DEPT_CODE 
FROM EMPLOYEE E, EMPLOYEE M
WHERE E.MANAGER_ID = M.EMP_ID(+);



/*
다중 조인 2개이상의 테이블을 조인하는것

*/
-- 직원번호 직원명 부서명 직급명 조회
--직원 부서  직급
-- 오라클 구문

SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME
FROM EMPLOYEE E, DEPARTMENT, JOB J
WHERE DEPT_CODE = DEPT_ID AND E.JOB_CODE = J.JOB_CODE;
ORDER BY EMP_ID;

--ANSI 구문

SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME
FROM EMPLOYEE E JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID JOIN JOB J ON E.JOB_CODE = J.JOB_CODE;

SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME
FROM EMPLOYEE E JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID JOIN JOB J USING (JOB_CODE);

---직원번호 직원명 부서명 지역명 
--오라클
SELECT EMP_ID, EMP_ID, DEPT_ID, LOCATION_ID, LOCAL_CODE
FROM EMPLOYEE, DEPARTMENT, LOCATION
WHERE DEPT_CODE = DEPT_ID AND LOCATION_ID = LOCAL_CODE;

--ANSI
SELECT EMP_ID, EMP_ID, DEPT_ID, LOCATION_ID, LOCAL_CODE
FROM EMPLOYEE  JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID JOIN LOCATION ON LOCATION_ID = LOCAL_CODE;
